---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
exclude_paths: 
