version: "3"
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    command: ["mongod", "--auth"]


  web:
    platform: linux/amd64
    build: .
    volumes:
      - .:/tomatoes
    tmpfs:
      - /tomatoes/tmp
    entrypoint: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DO_HOST=mongo
      - DURATION=${DURATION}
      - BREAK_DURATION=${BREAK_DURATION}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SENDGRID_USERNAME=${SENDGRID_USERNAME}
      - SENDGRID_PASSWORD=${SENDGRID_PASSWORD}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - EXCEPTION_RECIPIENTS=contato@dwcorp.com.br
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
