version: "3"
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017

  web:
    platform: linux/amd64
    build: .
    volumes:
      - .:/tomatoes
    tmpfs:
      - /tomatoes/tmp
    entrypoint: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - DO_HOST=mongo
      - DURATION=${DURATION}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SENDGRID_USERNAME=${SENDGRID_USERNAME}
      - SENDGRID_PASSWORD=${SENDGRID_PASSWORD}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
